const bcrypt = require("bcryptjs");
const { query, pool } = require("./db");

const DEMO_PRODUCTS = [
  { slug: "alq-cotton-ivory", name: "Signature Cotton — Ivory", category: "cotton", color: "Ivory", price: 2990, salePrice: null, image: "/images/home/gallery-fabric-1.webp", badge: "New", description: "A breathable cotton unstitched length with a soft hand-feel and a clean, versatile finish for custom tailoring.", fabric: "100% premium cotton", care: "Machine wash cold before stitching. Iron on medium heat.", material: "Premium Cotton", collection: "Core Cotton", tags: ["cotton", "unstitched", "ivory"], stock: 24 },
  { slug: "alq-cotton-stone", name: "Signature Cotton — Stone", category: "cotton", color: "Stone", price: 2890, salePrice: null, image: "/images/home/gallery-detail.webp", badge: null, description: "A refined stone cotton length designed for everyday tailoring, from relaxed daytime looks to polished occasion wear.", fabric: "100% premium cotton", care: "Machine wash cold before stitching. Do not bleach.", material: "Premium Cotton", collection: "Core Cotton", tags: ["cotton", "unstitched", "stone"], stock: 20 },
  { slug: "alq-cotton-midnight", name: "Signature Cotton — Midnight", category: "cotton", color: "Midnight", price: 3190, salePrice: 2890, image: "/images/home/gallery-model.webp", badge: "Sale", description: "A deep midnight cotton unstitched length with a smooth fall and enough structure for a sharp custom silhouette.", fabric: "100% premium cotton", care: "Hand wash separately in cold water for the first few washes.", material: "Premium Cotton", collection: "Core Cotton", tags: ["cotton", "unstitched", "midnight"], stock: 12 },
  { slug: "alq-cotton-sand", name: "Signature Cotton — Sand", category: "cotton", color: "Sand", price: 2990, salePrice: null, image: "/images/home/gallery-fabric-2.webp", badge: null, description: "A warm sand cotton length that brings a quiet, natural tone to a made-to-measure wardrobe.", fabric: "100% premium cotton", care: "Machine wash cold before stitching. Iron on medium heat.", material: "Premium Cotton", collection: "New Arrivals", tags: ["cotton", "unstitched", "sand"], stock: 18 },
  { slug: "alq-ww-black", name: "Wash & Wear — Black", category: "wash-n-wear", color: "Black", price: 3490, salePrice: null, image: "/images/home/hero-alqutuz.webp", badge: "Bestseller", description: "A low-maintenance black Wash & Wear length with a composed drape and an easy-care finish for the everyday wardrobe.", fabric: "65% polyester, 35% cotton Wash & Wear blend", care: "Machine washable. Minimal ironing needed.", material: "Premium Wash & Wear", collection: "Core Wash & Wear", tags: ["wash & wear", "unstitched", "black"], stock: 30, isBestseller: true },
  { slug: "alq-ww-charcoal", name: "Wash & Wear — Charcoal", category: "wash-n-wear", color: "Charcoal", price: 3390, salePrice: 3090, image: "/images/home/gallery-detail.webp", badge: "Sale", description: "A charcoal Wash & Wear length built for clean lines, reliable wear, and easy care from morning to evening.", fabric: "65% polyester, 35% cotton Wash & Wear blend", care: "Machine washable. Tumble dry low.", material: "Premium Wash & Wear", collection: "Core Wash & Wear", tags: ["wash & wear", "unstitched", "charcoal"], stock: 16 },
  { slug: "alq-ww-tobacco", name: "Wash & Wear — Tobacco", category: "wash-n-wear", color: "Tobacco", price: 3590, salePrice: null, image: "/images/home/gallery-fabric-2.webp", badge: "New", description: "A rich tobacco-toned Wash & Wear length with subtle depth, made for a confident custom finish.", fabric: "65% polyester, 35% cotton Wash & Wear blend", care: "Machine washable. Wash separately for the first wash.", material: "Premium Wash & Wear", collection: "New Arrivals", tags: ["wash & wear", "unstitched", "tobacco"], stock: 14 },
  { slug: "alq-ww-steel", name: "Wash & Wear — Steel Blue", category: "wash-n-wear", color: "Steel Blue", price: 3490, salePrice: null, image: "/images/home/gallery-fabric-1.webp", badge: null, description: "A cool steel blue Wash & Wear length with a polished surface and dependable everyday performance.", fabric: "65% polyester, 35% cotton Wash & Wear blend", care: "Machine washable. Minimal ironing needed.", material: "Premium Wash & Wear", collection: "Core Wash & Wear", tags: ["wash & wear", "unstitched", "steel blue"], stock: 22 },
];

async function main() {
  await query(`CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, fit TEXT NOT NULL DEFAULT 'unstitched', color TEXT NOT NULL, price NUMERIC NOT NULL, sale_price NUMERIC, sizes JSONB NOT NULL DEFAULT '[]', image TEXT NOT NULL, badge TEXT, description TEXT NOT NULL DEFAULT '', fabric TEXT NOT NULL DEFAULT '', care TEXT NOT NULL DEFAULT '', stock INTEGER NOT NULL DEFAULT 0, stock_by_size JSONB NOT NULL DEFAULT '{}', active BOOLEAN NOT NULL DEFAULT true, images JSONB NOT NULL DEFAULT '[]', video_url TEXT, tags JSONB NOT NULL DEFAULT '[]', sku TEXT, sku_by_size JSONB NOT NULL DEFAULT '{}', style_code TEXT, size_type TEXT NOT NULL DEFAULT 'standard', low_stock_threshold INTEGER NOT NULL DEFAULT 5, complete_the_look JSONB NOT NULL DEFAULT '[]', frequently_bought_with JSONB NOT NULL DEFAULT '[]', estimated_delivery TEXT, return_policy TEXT, material TEXT, stretch TEXT DEFAULT 'none', collection TEXT, is_bestseller BOOLEAN NOT NULL DEFAULT false)`);
  await query("UPDATE products SET active = false WHERE category NOT IN ('wash-n-wear', 'cotton')");
  for (const p of DEMO_PRODUCTS) {
    await query(`INSERT INTO products (slug,name,category,fit,color,price,sale_price,sizes,image,badge,description,fabric,care,stock,stock_by_size,active,images,video_url,tags,sku,sku_by_size,style_code,size_type,low_stock_threshold,complete_the_look,frequently_bought_with,estimated_delivery,return_policy,material,stretch,collection,is_bestseller)
      VALUES ($1,$2,$3,'unstitched',$4,$5,$6,'[]',$7,$8,$9,$10,$11,$12,'{}',true,$13,NULL,$14,$15,'{}',NULL,'standard',5,'[]','[]','3–5 working days in major cities, 5–7 elsewhere','Free exchange within 14 days of delivery, tags attached and unworn.',$16,'none',$17,$18)
      ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, fit='unstitched', color=EXCLUDED.color, price=EXCLUDED.price, sale_price=EXCLUDED.sale_price, sizes='[]', image=EXCLUDED.image, badge=EXCLUDED.badge, description=EXCLUDED.description, fabric=EXCLUDED.fabric, care=EXCLUDED.care, stock=EXCLUDED.stock, stock_by_size='{}', active=true, images=EXCLUDED.images, tags=EXCLUDED.tags, material=EXCLUDED.material, collection=EXCLUDED.collection, is_bestseller=EXCLUDED.is_bestseller`, [p.slug,p.name,p.category,p.color,p.price,p.salePrice,p.image,p.badge,p.description,p.fabric,p.care,p.stock,JSON.stringify([p.image]),JSON.stringify(p.tags),p.material,p.collection,Boolean(p.isBestseller)]);
  }
  const adminUser = process.env.ADMIN_INITIAL_USERNAME || "admin";
  const adminPass = process.env.ADMIN_INITIAL_PASSWORD || "change-me-now";
  const hash = await bcrypt.hash(adminPass, 10);
  await query(`INSERT INTO admin_users (username,password_hash,role,active) VALUES ($1,$2,'super_admin',true) ON CONFLICT (username) DO NOTHING`, [adminUser, hash]);
  console.log(`Seed complete: ${DEMO_PRODUCTS.length} AL-QUTUZ unstitched products`);
}
main().catch((err) => { console.error(err); process.exitCode = 1; }).finally(() => pool.end());
